hydra:
  job:
    chdir: false

experiment:
  method: arithmetic_test
  description: "Nothing to say."



models: 
  llama:
    class: hf
    init_args:
      name: 'llama'
      device: "cuda"
      default_training_mode: 'ppo'
      pretrained_args: 
        pretrained_model_name_or_path: "meta-llama/Meta-Llama-3.1-8B-Instruct"
        torch_dtype: "bfloat16"
        device_map: "cuda"
      bits_and_bytes_args:
        load_in_8bit: True
      lora_args:
        task_type: TaskType.CAUSAL_LM
        r: 32
        lora_alpha: 32
        lora_dropout: 0.1
        target_modules: "all-linear"
      ppo_trainer_class: PPOTrainer
      ppo_trainer_args: # see https://github.com/huggingface/trl/blob/main/trl/trainer/ppo_config.py
        batch_size: 64
        mini_batch_size: 1
        gradient_accumulation_steps: None
        ppo_epochs: 4
        #vf_coef: 0.1
        gradient_checkpointing: False
        log_with: "tensorboard"
        project_kwargs: None
        tracker_project_name: "tensorboard"
        #target_kl: 0.1
        #cliprange: 0.2
        #init_kl_coef: 0.2
        #learning_rate: 10e-5
        is_peft_model: True
      save_lora_weights: True
      lora_pretrained_path: null
      generation_args:
        max_new_tokens: 20
        do_sample: True
        temperature: 1.0
        top_k: 1000
        top_p: 0.9
        repetition_penalty: 1.0
      keep_vllm_during_training: False
      keep_hf_during_generation: False
      generate_with: "vllm"


players: 

  alice:
    id: 0
    dond_player_args:
      model_name: 'llama'
      game_intro_file: "src/prompts/dond/rules.txt"
      chain_of_thought_file: "src/prompts/dond/cot.txt" # false if none, else link to txt file 
      finalization_file: "src/prompts/dond/finalization.txt"
      new_round_file: "src/prompts/dond/new_round.txt"
      max_retries: 4
    ppo_data_extraction_args:
      last_k_responses: 1
      substract_mean_score: false


  bob:
    id: 1
    dond_player_args:
      model_name: 'llama'
      game_intro_file: "src/prompts/dond/rules.txt"
      chain_of_thought_file: "src/prompts/dond/cot.txt" # false if none, else link to txt file 
      finalization_file: "src/prompts/dond/finalization.txt"
      new_round_file: "src/prompts/dond//new_round.txt"
      max_retries: 4
    ppo_data_extraction_args:
      last_k_responses: 1
      substract_mean_score: false



    





