hydra:
  job:
    chdir: false

experiment:
  method: dond_nego_cycle
  description: "Nothing to say."

iterations:

  nb_iterations: 20
  iteration_runner_args:
    nb_parallel_games: 3
    games_per_iteration: 3

  dond_game_args:
    rounds_per_game: 1
    max_turns: 3
    player_order: deterministic # deterministic or random player who start beginning of each round
    mode: coop # basic, coop
    setup: manual # manual or random_read
    player_0_values: [20]
    player_1_values: [10]
    items: ['gold']
    quantities: [10]
    setups_file: src/environments/dond_setups.txt
    finalization_visibility: True


models: 
  llama:
    class: hf
    init_args:
      name: 'llama'
      device: "cuda"
      default_training_mode: 'ppo'
      pretrained_args: 
        pretrained_model_name_or_path: "meta-llama/Meta-Llama-3.1-8B-Instruct"
        torch_dtype: "bfloat16"
        device_map: "auto"
      bits_and_bytes_args:
        load_in_8bit: True
      lora_args:
        task_type: TaskType.CAUSAL_LM
        r: 8
        lora_alpha: 8
        lora_dropout: 0.1
        target_modules: "all-linear"
      ppo_trainer_class: PPOTrainer
      ppo_trainer_args: # see https://github.com/huggingface/trl/blob/main/trl/trainer/ppo_config.py
        batch_size: 32
        mini_batch_size: 1
        gradient_accumulation_steps: None
        ppo_epochs: 4
        #vf_coef: 0.1
        gradient_checkpointing: False
        log_with: "tensorboard"
        project_kwargs: None
        tracker_project_name: "tensorboard"
        #target_kl: 0.1
        #cliprange: 0.2
        #init_kl_coef: 0.2
        #learning_rate: 10e-5
        is_peft_model: True
      save_lora_weights: True
      lora_pretrained_path: null
      generation_args:
        max_new_tokens: 20
        do_sample: True
        temperature: 1.0
        top_k: 1000
        top_p: 0.9
        repetition_penalty: 1.0
      keep_vllm_during_training: False
      keep_hf_during_generation: True
      generate_with: "vllm"


players: 
  player_a:
    id: 0 # Will be used by game to determine which player starts
    dond_player_args:
      model_name: 'llama'
      game_intro_file: "src/prompts/dond/rules.txt"
      chain_of_thought_file: "src/prompts/dond/cot.txt" # false if none, else link to txt file 
      finalization_file: "src/prompts/dond/finalization.txt"
      new_round_file: "src/prompts/dond/new_round.txt"
      max_retries: 1
    ppo_data_extraction_args:
      last_k_responses: 1
      substract_mean_score: false


  player_b:
    id: 1
    dond_player_args:
      model_name: 'llama'
      game_intro_file: "src/prompts/dond/rules.txt"
      chain_of_thought_file: "src/prompts/dond/cot.txt" # false if none, else link to txt file 
      finalization_file: "src/prompts/dond/finalization.txt"
      new_round_file: "src/prompts/dond//new_round.txt"
      max_retries: 1
    ppo_data_extraction_args:
      last_k_responses: 1
      substract_mean_score: false



    





