hydra:
  job:
    chdir: false

experiment:
  method: dond_run_train
  description: "Easy. They should be learning."
  nb_iterations: 10
  nb_matches_per_iteration: 10
  reinit_matches_each_it: true

matches:

  stop_condition: game_over_condition
  stop_condition_kwargs: {}

  run_matches_args:
    nb_parallel_matches: -1
    log_func: independant_players_logging
    log_func_args: 
      metrics_func: gather_dond_statistics
      metrics_func_args: {} 
      training_data_func: set_discounted_returns
      training_data_func_args: {}

  dond_game_args:
    rounds_per_game: 1
    max_turns: 1
    mode: basic
    random_setup_func: fixed_manual
    random_setup_kwargs: 
      items: ['coins']
      quantities: [10]
      val_starting_negotiator: [1]
      val_responding_negotiator: [1]
    role_assignator_func: fixed_role_assignator
    role_assignator_func_kwargs: {}
    finalization_visibility: True
    other_values_visibility: True

  players: 

    alice:

      dond_player_args:
        mod_adpt_id: 'llama/ad_alice'
        allow_reasoning: false
        max_retries: 0

    bob:

      dond_player_args:
        mod_adpt_id: 'llama/ad_bob'
        allow_reasoning: false
        max_retries: 0


training:
  llama:
    adapters:
      ad_alice:
        train_func: train_reinforce_main
        train_func_args: 
          learning_rate: 1e5

      ad_bob:
        train_func: train_reinforce_main
        train_func_args: {}
              #learning_rate: 1e5


models: 

  llama:
    class: hf
    init_args:
      name: 'llama'
      adapter_names: ['ad_alice', 'ad_bob']
      include_value_head: false
      device: "cuda"
      pretrained_args: 
        pretrained_model_name_or_path: "meta-llama/Llama-3.1-8B-Instruct"
        torch_dtype: "bfloat16"
        device_map: "auto"
        attn_implementation: "flash_attention_2"
      bits_and_bytes_args: null
        #load_in_8bit: False
        #load_in_4bit: true
      lora_args:
        task_type: TaskType.CAUSAL_LM
        r: 32
        lora_alpha: 16
        lora_dropout: 0.0
        target_modules: ["q_proj", "k_proj"]

      generation_args:
        max_new_tokens: 200
        do_sample: True
        temperature: 1.
        
        top_k: 0.0
        top_p: 1.0
        repetition_penalty: 1.0
      keep_vllm_during_training: False
      keep_hf_during_training: True
      keep_hf_during_eval: False
      keep_vllm_during_eval: True
      eval_with: "vllm"
      train_with: "hf"

  








